#!/usr/bin/env bash
# 本地权限模式切换（无上游 Host 时用 fixture blob 做 PI 手动测试）。
#
# 用法（任意 cwd 均可）:
#   bash config/authz-manual-test/switch.sh <cmd>
#
# 命令:
#   on       开启权限：authz.mode=on + 有效 config/dev-auth.blob
#   off      关闭权限：authz.mode=off（不注入 data-auth）
#   deny     测拦截：authz.mode=on，但 blob 路径故意不存在
#   restore  恢复第一次切换前的 harness-config.yaml
#   status   查看当前 authz / blob / CLI
#   help     显示本帮助
#
# 行为要点:
#   - 首次 on|off|deny 前会备份当前 config 到 harness-config.baseline.yaml
#   - 切换时保留已有 cli.* 路径（不写 /absolute/path 占位符）
#   - on 时从 config/fixtures/local-test-auth.blob 复制工作副本 dev-auth.blob
#   - config/harness-config.yaml 与 config/dev-auth.blob 均 gitignore
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CFG="$ROOT/config/harness-config.yaml"
ENV_FILE="$ROOT/config/qdm-cli-paths.env"
DIR="$ROOT/config/authz-manual-test"
BASELINE="$DIR/harness-config.baseline.yaml"
BLOB_WORK="$ROOT/config/dev-auth.blob"
BLOB_FIXTURE="$ROOT/config/fixtures/local-test-auth.blob"
DEV_USER_ID="local-test-user"

usage() {
  sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
}

# --- helpers ---

yaml_get() {
  # yaml_get <file> <key>  — 取顶层/缩进键的简单标量值（无嵌套解析）
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  # 匹配 "  key: value" 或 "key: value"，去掉行内注释
  sed -nE "s/^[[:space:]]*${key}:[[:space:]]*([^#]*).*/\1/p" "$file" | head -1 | sed -E 's/[[:space:]]+$//'
}

is_placeholder_path() {
  local p="${1:-}"
  [[ -z "$p" || "$p" == /absolute/path/* || "$p" == *"/absolute/path/"* ]]
}

# 解析 cli 路径：优先现有 config 非占位值 → bin 下存在的路径 → 默认相对路径
resolve_cli_path() {
  local key="$1" default_rel="$2"
  local cur=""
  cur="$(yaml_get "$CFG" "$key" 2>/dev/null || true)"
  if ! is_placeholder_path "$cur"; then
    printf '%s' "$cur"
    return
  fi
  if [[ -e "$ROOT/$default_rel" || -L "$ROOT/$default_rel" ]]; then
    printf '%s' "$default_rel"
    return
  fi
  printf '%s' "$default_rel"
}

ensure_baseline() {
  if [[ -f "$BASELINE" ]]; then
    return
  fi
  if [[ -f "$CFG" ]]; then
    cp "$CFG" "$BASELINE"
    echo "saved baseline → ${BASELINE#$ROOT/}"
  fi
}

ensure_local_blob() {
  if [[ ! -f "$BLOB_FIXTURE" ]]; then
    echo "error: fixture missing: ${BLOB_FIXTURE#$ROOT/}" >&2
    echo "  expected committed config/fixtures/local-test-auth.blob" >&2
    exit 1
  fi
  if [[ -f "$BLOB_WORK" ]]; then
    # 已有工作副本则保留（可能是用户自生成的）
    echo "blob: keep existing ${BLOB_WORK#$ROOT/}"
    return
  fi
  cp "$BLOB_FIXTURE" "$BLOB_WORK"
  echo "blob: copied fixtures/local-test-auth.blob → config/dev-auth.blob"
}

write_harness_config() {
  local mode="$1" blob_file="$2"
  local metric knowledge

  knowledge="$(yaml_get "$CFG" "knowledge" 2>/dev/null || true)"
  [[ -z "$knowledge" ]] && knowledge="wikis"

  metric="$(resolve_cli_path qdm_metric_cli "bin/qdm-metric-cli")"

  cat >"$CFG" <<EOF
# Generated by config/authz-manual-test/switch.sh (profile: ${mode})
# Do not commit. Restore baseline: bash config/authz-manual-test/switch.sh restore

paths:
  knowledge: ${knowledge}

cli:
  qdm_metric_cli: ${metric}

authz:
  mode: ${mode}
  blob_file: ${blob_file}
  # Explicit local principal for file-mode only (not a product default identity).
  dev_user_id: ${DEV_USER_ID}
  allow_local_blob: true
EOF
  echo "wrote ${CFG#$ROOT/}"
}

# 同步 qdm-cli-paths.env 的 metric 为仓库 bin 绝对路径
ensure_cli_env() {
  local metric_abs="$ROOT/bin/qdm-metric-cli"

  if [[ ! -f "$ENV_FILE" ]]; then
    cat >"$ENV_FILE" <<EOF
export QDM_METRIC_CLI="${metric_abs}"
EOF
    echo "wrote ${ENV_FILE#$ROOT/}"
    return
  fi

  upsert_env() {
    local key="$1" val="$2"
    local tmp
    tmp="$(mktemp)"
    if grep -q "^export ${key}=" "$ENV_FILE"; then
      sed "s|^export ${key}=.*|export ${key}=\"${val}\"|" "$ENV_FILE" >"$tmp"
      mv "$tmp" "$ENV_FILE"
    else
      rm -f "$tmp"
      echo "export ${key}=\"${val}\"" >>"$ENV_FILE"
    fi
  }

  upsert_env QDM_METRIC_CLI "$metric_abs"
  # Drop retired SQL/CAS env exports if present
  if grep -qE '^export QDM_(SQL_CLI|CAS_CLI|CAS_CONFIG_DIR)=' "$ENV_FILE"; then
    local tmp
    tmp="$(mktemp)"
    grep -vE '^export QDM_(SQL_CLI|CAS_CLI|CAS_CONFIG_DIR)=' "$ENV_FILE" >"$tmp"
    mv "$tmp" "$ENV_FILE"
  fi
}

warn_missing_bins() {
  if [[ ! -e "$ROOT/bin/qdm-metric-cli" && ! -L "$ROOT/bin/qdm-metric-cli" ]]; then
    echo "warn: bin/qdm-metric-cli 不存在 — PI 跑 metric 会失败；可 ln -s <path> bin/qdm-metric-cli" >&2
  fi
  if [[ ! -e "$ROOT/bin/data-harness-cli" && ! -L "$ROOT/bin/data-harness-cli" ]]; then
    echo "warn: bin/data-harness-cli 不存在 — PI context 会失败；chmod 755 bin/data-harness-cli" >&2
  fi
}

# 校验当前 config 能否被 data-harness-cli 解析（旧二进制会拒 qdm_metric_cli/authz）
doctor_harness_cli() {
  local cli="$ROOT/bin/data-harness-cli"
  if [[ ! -x "$cli" && ! -L "$cli" ]]; then
    echo "doctor data-harness-cli: missing"
    return 1
  fi
  local err
  err="$(
    cd "$ROOT" && printf '%s' '{"session_id":"switch-doctor","prompt":"ping"}' |
      "$cli" context --format agent-hook 2>&1 >/dev/null
  )" || true
  # 成功时通常无 stderr；失败会打印 unsupported key / 其它错误
  if [[ -z "$err" ]]; then
    echo "doctor data-harness-cli: ok (parses harness-config + context)"
    return 0
  fi
  # context 可能因索引等问题非 0，但若报 unsupported 一定是二进制过旧
  if grep -q 'unsupported' <<<"$err"; then
    echo "doctor data-harness-cli: STALE — $err" >&2
    echo "  fix: chmod 755 bin/data-harness-cli" >&2
    return 1
  fi
  # 其它错误也提示，但不一定是 switch 问题
  echo "doctor data-harness-cli: warn — ${err//$'\n'/; }"
  return 0
}

doctor_metric_cli() {
  local cli="$ROOT/bin/qdm-metric-cli"
  if [[ ! -e "$cli" && ! -L "$cli" ]]; then
    echo "doctor qdm-metric-cli: missing"
    return 1
  fi
  local help
  help="$("$cli" auth describe --help 2>&1 || true)"
  if grep -qE 'auth describe|--auth-blob' <<<"$help"; then
    echo "doctor qdm-metric-cli: ok (has auth describe)"
    return 0
  fi
  echo "doctor qdm-metric-cli: STALE — no auth describe (rebuild qdm-metric-cli)" >&2
  echo "  fix: (cd ../qdm-metric-cli && go build -o dist/qdm-metric-cli ./cmd/qdm-metric-cli)" >&2
  return 1
}

show_status() {
  echo "repo:    $ROOT"
  echo "config:  ${CFG#$ROOT/}"
  if [[ ! -f "$CFG" ]]; then
    echo "  (missing)"
    return 1
  fi

  local mode blob_file dev_user metric
  mode="$(yaml_get "$CFG" mode)"
  blob_file="$(yaml_get "$CFG" blob_file)"
  dev_user="$(yaml_get "$CFG" dev_user_id)"
  metric="$(yaml_get "$CFG" qdm_metric_cli)"

  echo "authz:"
  echo "  mode:          ${mode:-<unset>}"
  echo "  blob_file:     ${blob_file:-<unset>}"
  echo "  dev_user_id:   ${dev_user:-<unset>}"
  echo "  allow_local:   $(yaml_get "$CFG" allow_local_blob)"
  echo "cli.qdm_metric_cli: ${metric:-<unset>}"

  if [[ -n "${blob_file:-}" ]]; then
    local blob_abs
    if [[ "$blob_file" = /* ]]; then
      blob_abs="$blob_file"
    else
      blob_abs="$ROOT/$blob_file"
    fi
    if [[ -f "$blob_abs" ]]; then
      local prefix
      prefix="$(head -c 24 "$blob_abs" 2>/dev/null || true)"
      echo "blob file:     present (${blob_file}) prefix=${prefix}..."
    else
      echo "blob file:     MISSING (${blob_file})"
    fi
  fi

  if [[ -f "$BASELINE" ]]; then
    echo "baseline:      ${BASELINE#$ROOT/} (restore 可用)"
  else
    echo "baseline:      (尚未备份；首次 on|off|deny 会自动保存)"
  fi

  echo "env HARNESS_AUTH_BLOB=${HARNESS_AUTH_BLOB:-<unset>}"
  echo "env HARNESS_AUTH_USER_ID=${HARNESS_AUTH_USER_ID:-<unset>}"
  echo "env HARNESS_AUTH_BLOB_FILE=${HARNESS_AUTH_BLOB_FILE:-<unset>}"
  if [[ -f "$ENV_FILE" ]]; then
    grep -E '^export QDM_METRIC_CLI=' "$ENV_FILE" || true
  else
    echo "env file:      missing ${ENV_FILE#$ROOT/}"
  fi

  if [[ -e "$ROOT/bin/qdm-metric-cli" || -L "$ROOT/bin/qdm-metric-cli" ]]; then
    echo "bin/qdm-metric-cli: ok → $(readlink "$ROOT/bin/qdm-metric-cli" 2>/dev/null || echo file)"
  else
    echo "bin/qdm-metric-cli: missing"
  fi

  # 自检：避免 switch on 后 PI 因旧 CLI 挂掉
  doctor_harness_cli || true
  doctor_metric_cli || true
}

# --- main ---

profile="${1:-}"
case "$profile" in
  on)
    ensure_baseline
    ensure_local_blob
    write_harness_config "on" "config/dev-auth.blob"
    ensure_cli_env
    warn_missing_bins
    echo "OK: authz ON（local-test-user + config/dev-auth.blob）"
    ;;
  off)
    ensure_baseline
    write_harness_config "off" "config/dev-auth.blob"
    ensure_cli_env
    echo "OK: authz OFF（不注入 data-auth）"
    ;;
  deny)
    ensure_baseline
    # 故意指向不存在文件，hook 应 block
    write_harness_config "on" "config/dev-auth.blob.MISSING"
    ensure_cli_env
    echo "OK: authz DENY（mode=on 但 blob 缺失，用于测拦截）"
    ;;
  restore)
    if [[ -f "$BASELINE" ]]; then
      cp "$BASELINE" "$CFG"
      echo "OK: restored from baseline (${BASELINE#$ROOT/})"
    elif [[ -f "$DIR/harness-config.restore.yaml" ]]; then
      cp "$DIR/harness-config.restore.yaml" "$CFG"
      echo "OK: restored from harness-config.restore.yaml（无 baseline）"
    else
      write_harness_config "off" "config/dev-auth.blob"
      echo "OK: no baseline; wrote authz OFF default"
    fi
    ensure_cli_env
    ;;
  status)
    show_status
    exit 0
    ;;
  help|-h|--help)
    usage
    exit 0
    ;;
  *)
    echo "usage: $0 on|off|deny|restore|status|help" >&2
    exit 2
    ;;
esac

echo "---"
show_status
